name: Bug Report
description: Found something you weren't expecting? Report it here!
labels: ["type/bug"]
body:
  - type: markdown
    attributes:
      value: |
        NOTE: If your issue is a security concern, please send an email to contact@mengning.com.cn instead of opening a public issue.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please provide a description of your issue here.
  - type: input
    id: devstar-ver
    attributes:
      label: DevStar Version
      description: DevStar version (or commit reference) of your instance
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If this issue involves the Web Interface, please provide one or more screenshots
  - type: input
    id: git-ver
    attributes:
      label: Git Version
      description: The version of git running on the server
  - type: input
    id: os-ver
    attributes:
      label: Operating System
      description: The operating system you are using to run DevStar
  - type: textarea
    id: run-info
    attributes:
      label: How are you running DevStar?
      description: |
        Please include information on whether you built DevStar yourself, used one of our downloads, are using https://devstar.cn or are using some other package
        Please also tell us how you are running DevStar, e.g. if it is being run from docker, a command-line, systemd etc.
        If you are using a package or systemd tell us what distribution you are using
    validations:
      required: true
  - type: dropdown
    id: database
    attributes:
      label: Database
      description: What database system are you running?
      options:
        - PostgreSQL
        - MySQL/MariaDB
        - MSSQL
        - SQLite
