name: Web Interface Bug Report
description: Something doesn't look quite as it should?  Report it here!
labels: ["type/bug", "topic/ui"]
body:
  - type: markdown
    attributes:
      value: |
        NOTE: If your issue is a security concern, please send an email to contact@mengning.com.cn instead of opening a public issue.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please provide a description of your issue here, with a URL if you were able to reproduce the issue (see below)
        If using a proxy or a CDN (e.g. CloudFlare) in front of gitea, please disable the proxy/CDN fully and connect to gitea directly to confirm the issue still persists without those services.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please provide at least 1 screenshot showing the issue.
    validations:
      required: true
  - type: input
    id: devstar-ver
    attributes:
      label: DevStar Version
      description: DevStar version (or commit reference) your instance is running
    validations:
      required: true
  - type: dropdown
    id: can-reproduce
    attributes:
      label: Can you reproduce the bug on the DevStar demo site?
      description: |
        If so, please provide a URL in the Description field
        URL of DevStar demo: https://devstar.cn
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: input
    id: os-ver
    attributes:
      label: Operating System
      description: The operating system you are using to access DevStar
  - type: input
    id: browser-ver
    attributes:
      label: Browser Version
      description: The browser and version that you are using to access DevStar
    validations:
      required: true
