# This is a basic workflow to help you get started with Actions

name: Push DevStar Image to DockerHub

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:  
      - name: Pull DevStar Image  
        run: |  
          docker pull mengning997/devstar-studio:latest
          docker pull mengning997/webterminal:latest
          docker pull mengning997/act_runner:latest
          docker pull devstar.cn/devstar/act_runner:latest
          docker pull devstar.cn/devstar/webterminal:latest
          docker pull devstar.cn/devstar/devstar-studio:latest 

      - name: Log in to Target Docker Registry  
        uses: docker/login-action@v2  
        with:  
          registry: docker.io  # 替换为目标镜像仓库  
          username: ${{ secrets.DOCKER_USERNAME }}  # 目标仓库用户名  
          password: ${{ secrets.DOCKER_PASSWORD }}  # 目标仓库密码  

      - name: Tag Docker Image for Target Registry  
        run: |  
          docker tag devstar.cn/devstar/devstar-studio:latest  mengning997/devstar-studio:latest  # 替换为目标镜像名称和标签
          docker tag devstar.cn/devstar/webterminal:latest  mengning997/webterminal:latest
          docker tag devstar.cn/devstar/act_runner:latest  mengning997/act_runner:latest

      - name: Push Docker Image to Target Registry  
        run: |  
          docker push mengning997/devstar-studio:latest  # 替换为目标镜像名称和标签
          docker push mengning997/webterminal:latest
          docker push mengning997/act_runner:latest
