name: Push DevStar Image to DockerHub

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      IMAGE_NAME:
        description: 'Docker image name'
        required: false
        type: string
        default: 'devstar-studio:latest'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Install skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo
      
      - name: Login to source registry (devstar.cn)
        run: |
          skopeo login devstar.cn \
            --username ${{ secrets.DEVSTAR_USERNAME }} \
            --password ${{ secrets.DEVSTAR_PASSWORD }}
      
      - name: Login to target registry (Docker Hub)
        run: |
          skopeo login docker.io \
            --username ${{ secrets.DOCKER_USERNAME }} \
            --password ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Copy image
        run: |
          skopeo copy --all \
            --src-tls-verify=false \
            --dest-tls-verify=true \
            docker://devstar.cn/devstar/${{ github.event.inputs.IMAGE_NAME }} \
            docker://devstarcn/${{ github.event.inputs.IMAGE_NAME }}
