# This is a basic workflow to help you get started with Actions

name: Test install.sh

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          wget -c https://gitee.com/devstar/devstar/raw/add-intaller-tool/public/assets/install.sh && chmod +x install.sh && sudo ./install.sh
          sudo devstar start --version=latest --port=8888
      
      # Wait for a few seconds to ensure the service has time to start  
      - name: Wait for the service to start  
        run: sleep 10  # 你可以根据实际需要调整等待时间  

      # Check if the service is accessible  
      - name: Verify HTTP accessibility  
        run: |  
          RESPONSE=$(curl --write-out '%{http_code}' --silent --output /dev/null http://localhost:8888)  
          if [ "$RESPONSE" -eq 200 ]; then  
            echo "Service is accessible!"  
          else  
            echo "Service is not accessible. HTTP response code: $RESPONSE"  
            exit 1  
          fi 
